# Full configuration: https://github.com/eko/FeedBundle
eko_feed:
    feeds:
        news:
            title:       'News'
            description: 'Latest news'
            link:
                route_name: news
            encoding:    'utf-8'
            author:      '' # Only required for Atom feeds
