# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    resolvers:
        default:
            web_path:
                cache_prefix: images/cache

    filter_sets:
        cache: ~

        thumbnail_small:
            filters:
                thumbnail:
                    size: [ 200, 200 ]
                    mode: inbound
                    allow_upscale: true

        news_header:
            filters:
                scale:
                    dim: [ 470, 240 ]