twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    form_themes: ['form/klms_bootstrap_4_layout.html.twig']
    globals:
        nav: '@App\Service\NavService'
        textblock: '@App\Service\TextBlockService'
