vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        news:
            uri_prefix: /images/news
            upload_destination: '%kernel.project_dir%/public/images/news'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        media:
            uri_prefix: /media
            upload_destination: '%kernel.project_dir%/public/media'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            directory_namer:
                service: Vich\UploaderBundle\Naming\PropertyDirectoryNamer
                options: { property: 'getMediaType' }
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        user:
            uri_prefix: /images/user
            upload_destination: '%kernel.project_dir%/public/images/user'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        setting:
            uri_prefix: /images/site
            upload_destination: '%kernel.project_dir%/public/images/site'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        sponsor:
            uri_prefix: /images/sponsor
            upload_destination: '%kernel.project_dir%/public/images/sponsor'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

# set different upload destination for testing
when@test:
    vich_uploader:
        mappings:
            news:
                upload_destination: '%kernel.cache_dir%/vich_data/images/news'
            media:
                upload_destination: '%kernel.cache_dir%/vich_data/media'
            user:
                upload_destination: '%kernel.cache_dir%/vich_data/images/user'
            setting:
                upload_destination: '%kernel.cache_dir%/vich_data/images/site'
            sponsor:
                upload_destination: '%kernel.cache_dir%/vich_data/images/sponsor'
