services:
  database:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: 'krru'
      POSTGRES_PASSWORD: 'krru'
      POSTGRES_DB: 'klms'
    ports: [ "5432:5432" ]
    volumes:
      - database:/var/lib/postgresql/data:rw
  
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1025:1025"
      - "1080:1080"
    labels:
      com.symfony.server.service-prefix: 'MailCatcher'
  
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: 'krru@krru.at'
      PGADMIN_DEFAULT_PASSWORD: 'admin'
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    labels:
      com.symfony.server.service-prefix: 'pgAdmin'

volumes:
  database:
  pgadmin:
