site:
    resource: ../../src/Controller/Site
    type: annotation

admin:
    resource: ../../src/Controller/Admin
    prefix: /admin
    name_prefix: admin_
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
